services:
    ticket.order.validator:
        class: TicketBundle\Validator\Order\OrderValidator
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: ticket.order.validator }
