<?php

namespace TicketBundle\Repository;

/**
 * TicketOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function canAddTickets($availableTickets, $ticket)
    {
        $em = $this->getEntityManager();
        $builder = $em->createQueryBuilder();
        $builder
            ->select('SUM(t.ticketsNumber) as ticketsNumber')
            ->from('TicketBundle\Entity\TicketOrder', 't');

        $query = $builder->getQuery();
        $results = $query->getOneOrNullResult();
        $good = true;

        if ($results['ticketsNumber'] + $ticket > $availableTickets) {
            $good = false;
        }

        return $good;
    }
}
